### ISSUE TITLE
Unable to use RDATAC mode

### ISSUE THREAD

**Issue by kaskavalci** [Flydroid/ADS12xx-Library#3]
Hello, 

I modified your code a bit to be able to use RDATAC in a for loop. 

``` cpp
long ads12xx::GetContConversion(int32_t buffer[], uint16_t len) {
  SPI.beginTransaction(SPISettings(SPI_SPEED, MSBFIRST, SPI_MODE1));

  digitalWrite(_CS, LOW); // Pull SS Low to Enable Communications with
  SPI.transfer(RDATAC);
  delayMicroseconds(10); // RD: Wait 25ns for ADC12xx to get ready

  for (size_t i = 0; i < len; ++i) {
    waitforDRDY(); // Wait until DRDY is LOW

    buffer[i] |= SPI.transfer(NOP);
    buffer[i] <<= 8;
    buffer[i] |= SPI.transfer(NOP);
    buffer[i] <<= 8;
    buffer[i] |= SPI.transfer(NOP);
  }

  SPI.transfer(SDATAC);

  digitalWrite(_CS, HIGH);
  SPI.endTransaction();
}
```

However I read random values sometimes. I changed `RDATA` in `GetConverstion` function to RDATAC to see how it behaves, unfortunately it behaves the same. 

I wonder what I'm doing wrong here. Any help is appreciated.

**Comment by Flydroid** [comment]
Hi,
Thanks for the comment! I haven't come to implement the RDATAC functionality because my application needs to switch between channels for every read.
Did you check if your circuit works with my standard function? Or try reading some of the interal sensors. That will eliminate external circuit errors.
Also there should be a waitforDRDY() before sending the SDATAC byte.

Hope this helps some.

**Comment by kaskavalci** [comment]
Hi, 

Thanks for your prompt response! Yes I tried with calling `waitforDRDY()` before sending SDATAC as well but didn't make a difference. 

Your `GetConverstion` works fine. However if I add RDATAC instead of RDATA there (and calling SDATAC in the end) your function doesn't work then. Even though it only reads once, RDATAC somehow produces corrupt results. Can you try adding RDATAC on your project and see how it behaves? I wonder if my hardware is somehow corrupted. 

PS: We utilize Arduino Uno and ADS1256.

**Comment by Flydroid** [comment]
Hi 
That is really wierd... because the instructions in the data sheet are quite streigth forward.
I'm sorry that i can't help more but i just don't have the time right know to do further testing myself.
I have had such wierd problems with these adc's all the time and mostly it was some error on my side, code-wise or hardware. One thing i could suspect is to try and play around with the delayMicroseconds(x). 

The Arduino shouldn't be that different from a teensy.... check if DRDY is on interrupt-able pin on the uno.

**Comment by baettigp** [comment]
Hi,
try sending 

#define RDATA   0x30    //Channel data read command (register format, set MUL=1, status byte included in data) data sheet CDRC
instead of just 0x20.

I got that info on the TI forums "Additionally, RDATA (0x20) ought to be (0x30) to set the MUL bit high."
https://e2e.ti.com/support/data_converters/precision_data_converters/f/73/p/485242/1750939

My code is now working on a MSP430F5529 in energia, I think I had a problem with the power up sequence some days ago.

**Comment by dizcza** [comment]
Sorry for reviving an old thread, but has anyone managed to run this ads1256 in continuous mode?
